title: 果粉部落
subtitle: 果粉部落
description: 果粉部落，只分享苹果教程
keywords: 苹果教程
author: naive
language: zh-CN
timezone: Asia/Shanghai

url: https://g0f.cn/
permalink: :year/:month/:day/:hash/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: butterfly
 #theme: anzhiyu

source_dir: source
public_dir: public
tag_dir: 标签
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: true
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

syntax_highlighter: highlight.js
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''

# marked:
#   gfm: true
#   pedantic: false
#   breaks: true
#   smartLists: true
#   smartypants: true
#   quotes: '“”‘’'
#   modifyAnchors: 0
#   anchorAlias: true
#   autolink: true
#   mangle: true
#   sanitizeUrl: false
#   dompurify: false
#   headerIds: true
#   lazyload: true
#   prependRoot: true
#   postAsset: true
#   external_link:
#     enable: true
#     exclude: []
#     nofollow: true
#   disableNunjucks: false
#   descriptionLists: true

markdown:
  preset: "default" # 渲染器默认预设 # "commonmark": 使用严格 CommandMark 规定. # "": 默认配置, 类似于 GFM # "zero": 禁用所有预设.
  # 以下为 render 选项
  render:
    html: true # 是否解析 HTML 内容, 如果为 true 则表示解析, false 表示将 HTML 转意为文本.
    xhtmlOut: false # 将 HTML 内容渲染为 XHTML 的形式 (XHTML 语法非常严格, 比如原 HTML 中的 <br> 标签必须要使用 <br/> 这样的形式进行 "自闭和") 可能会出现兼容性问题.
    langPrefix: "language-" # 只适用 Hexo 默认的两个高亮插件禁用时 # 为围栏代码块中语法定义选项渲染后自动添加 class 名前缀, 如 ---html 渲染为 <class="language-html">
    breaks: false # true 则将所有换行渲染为 <br> 标签 # 这种行为不属于 CommandMark 和 GFM.
    linkify: true # true 则自动解析链接并添加为 <a> 标签, false 则将链接渲染为文本.
    typographer: true # 默认 true # 自动转义各种排版用字符, 如 ©
    quotes: '“”‘’' # 当 typographer 定义为 true 时的自动转换引号的行为, quotes: '“”‘’' 则表示将 "123" '123'转换为 “123” ‘123’
  # render 选项到此结束
  enable_rules:
  disable_rules:
  # 当 preset 定义时的渲染规则 # "zero" 表示禁用所有规则而能单独启用规则 # "default" 表示启用所有规则, 所以只能禁用特定规则. # "commandmark" 将严格遵循 CommandMark 因此不能额外定义规则的启闭.
  # 使用单条规则
  # disable_rules: 'link'
  # 使用多条规则
  # disable_rules:
  #    - 'link'
  #    - 'image'
  plugins: # 插件选项
    - markdown-it-abbr # https://github.com/markdown-it/markdown-it-abbr
    - markdown-it-cjk-breaks # https://github.com/markdown-it/markdown-it-cjk-breaks
    - markdown-it-container # https://github.com/markdown-it/markdown-it-container
    - markdown-it-deflist # https://github.com/markdown-it/markdown-it-deflist
    - markdown-it-emoji # https://github.com/markdown-it/markdown-it-emoji
    - markdown-it-footnote # https://github.com/markdown-it/markdown-it-footnote
    - markdown-it-ins # https://github.com/markdown-it/markdown-it-ins
    - markdown-it-mark # https://github.com/markdown-it/markdown-it-mark
    - markdown-it-sub # https://github.com/markdown-it/markdown-it-sub
    - markdown-it-sup # https://github.com/markdown-it/markdown-it-sup
    #以下为额外安装插件
    - markdown-it-task-lists # https://github.com/revin/markdown-it-task-lists
  anchors: # 锚点的配置
    level: 2 # 开始创建锚点的等级 # 如 "2" 则表示从 H2 开始创建一直到 H6(最后).
    collisionSuffix: "" # 如果遇到重复的锚点 ID 为其添加数字编号时在这个数字后添加的后缀.
    # 以下为标题锚点配置
    permalink: true # false # 如果为 true 则创建一个除标题外带有固定地址的的锚点标签.
    permalinkClass: "fa-solid fa-hashtag" # 定义固定锚点的 class 名.
    permalinkSide: "right" # 设定为 right 则会在标题后添加固定链接.
    permalinkSymbol: "" # 定义固定链接使用的符号
    # 标题固定锚点到此结束
    case: 0 # 转换锚点 ID 中的字母为大写或小写 # "0" 不转换, "1" 为小写, "2" 为大写.
    separator: "-" # 用于替换空格的符号. # 默认为 "-"
  images:
    lazyload: true
    prepend_root: true
    post_asset: true
  inline: false

stylus:
  compress: true
  # sourcemaps:
  #   comment: true
  #   inline: true
  #   sourceRoot: ""
  #   basePath: .
  # plugins: "nib"

index_generator:
  path: ""
  per_page: 10
  order_by: -date

archive_generator:
  enabled: true
  per_page: 0
  yearly: true
  monthly: false
  daily: false
  order_by: -date

category_generator:
  per_page: 0
  order_by: -date

tag_generator:
  per_page: 0
  order_by: -date

default_category:
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 0
pagination_dir: page

include:
exclude:
ignore:

feed:
  enable: true
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss.xml
  limit: 5
  hub:
  content: true
  content_limit: false
  content_limit_delim: " "
  order_by: -updated
  icon: https://cdn.jsdelivr.net/gh/g0fcn/img/logo.webp
  autodiscovery: true
  template:
    - ./scaffolds/rss/atom.xml
    - ./scaffolds/rss/rss.xml

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  template:
  rel: true
  tags: false
  categories: false

search:
  path: search.json
  field: 全部
  content: true

algolia:
  appId: "NWLBXB1RFA"
  applicationID: "NWLBXB1RFA"
  apiKey: "94c3a9823bae81f7b3e6b6339d8a1b6d"
  totalPages: "1"
  per_page: "100"
  chunkSize: 5000
  indexName: "g0f"
  fields:
    - title
    - content:strip
    - path

nofollow:
  enable: true
  field: site
  exclude:
    - "g0f.cn"
    - "www.g0f.cn"

mmedia:
  audio:
    default:
      controls: true
  video:
    default:
      controls: true
  aplayer:
    js: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    css: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
    default:
      contents:
        lrcType: 3
  meting:
    js: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js
    api: https://music.startly.cn/ # https://meting.g0f.cn/api （备用，支持 YouTube Spotify）
    default:
      theme: '#8fbc8f'
      list-folded: true
  dplayer:
    js: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
    hls_js: https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js
    dash_js: https://cdn.jsdelivr.net/npm/dashjs/dist/dash.all.min.js
    shaka_dash_js: https://cdn.jsdelivr.net/npm/shaka-player/dist/shaka-player.compiled.js
    flv_js: https://cdn.jsdelivr.net/npm/flv.js/dist/flv.min.js
    webtorrent_js: https://cdn.jsdelivr.net/npm/webtorrent/webtorrent.min.js
    default:
      contents:
  artplayer:
    js: https://cdn.jsdelivr.net/npm/artplayer/dist/artplayer.js
    hls_js: https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js
    dash_js: https://cdn.jsdelivr.net/npm/dashjs/dist/dash.all.min.js
    shaka_dash_js: https://cdn.jsdelivr.net/npm/shaka-player/dist/shaka-player.compiled.js
    flv_js: https://cdn.jsdelivr.net/npm/flv.js/dist/flv.min.js
    webtorrent_js: https://cdn.jsdelivr.net/npm/webtorrent/webtorrent.min.js
    default:
      style: width:344px;height:193.5px
      contents:
        theme: "#8FBC8F"
        lang: zh-cn
        volume: 1
        isLive: false
        muted: false
        autoplay: false
        pip: true
        autoSize: true
        autoMini: false
        screenshot: false
        setting: true
        loop: false
        flip: true
        rotate: true
        playbackRate: true
        aspectRatio: true
        fullscreen: true
        fullscreenWeb: true
        subtitleOffset: true
        miniProgressBar: true
        localVideo: true
        localSubtitle: true
        networkMonitor: true
        mutex: true
        light: true
        backdrop: true
        playsInline: true
        autoPlayback: false
        whitelist: ['*']
        lock: true
        fastForward: false
        autoOrientation: true
  bilibili:
    default:
      page: 1
      danmaku: true
      allowfullscreen: allowfullscreen
      sandbox: allow-top-navigation allow-same-origin allow-forms allow-scripts allow-popups
      width: 100%
      max_width: 850px
      margin: auto
  xigua:
    default:
      autoplay: false
      startTime: 0
      allowfullscreen: allowfullscreen
      sandbox: allow-top-navigation allow-same-origin allow-forms allow-scripts allow-popups
      width: 100%
      max_width: 850px
      margin: auto

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签开关
  link:
    placeholder: https://cdn.jsdelivr.net/gh/g0fcn/img/logo.webp #link_card标签默认的图标图片
  CDN:
    anima: https://cdn.jsdelivr.net/npm/hexo-butterfly-tag-plugins-plus/lib/assets/font-awesome-animation.min.css #动画标签anima的依赖
    # jquery: https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js #issues标签依赖
    # issues: https://cdn.jsdelivr.net/npm/hexo-butterfly-tag-plugins-plus/lib/assets/issues.js #issues标签依赖
    iconfont: false #参看https://akilar.top/posts/d2ebecef/
    carousel: false #https://cdn.jsdelivr.net/npm/hexo-butterfly-tag-plugins-plus/lib/assets/carousel-touch.js
    tag_plugins_css: https://cdn.jsdelivr.net/npm/hexo-butterfly-tag-plugins-plus/lib/tag_plugins.css

wowjs:
  enable: false #控制动画开关。true是打开，false是关闭
  priority: 10 #过滤器优先级
  mobile: false #移动端是否启用，默认移动端禁用
  animateitem:
    - class: recent-post-item #必填项，需要添加动画的元素的class
      style: animate__zoomIn #必填项，需要添加的动画
      duration: 2秒 #选填项，动画持续时间，单位可以是ms也可以是s。例如3s，700ms。
      delay: 1秒 #选填项，动画开始的延迟时间，单位可以是ms也可以是s。例如3s，700ms。
      offset: 100 #选填项，开始动画的距离（相对浏览器底部）
      iteration: 2 #选填项，动画重复的次数
    - class: card-widget
      style: animate__zoomIn

minify:
  enable: true
  html:
  css:
  js:
  svg:
  gzip:
    enable: false
  brotli:
    enable: false
  xml:
    enable: true
  json:
    enable: false

webpushr:
  enable: true

  # webpushrKey: "webpushrKey"
  # webpushrAuthToken: "webpushrAuthToken"
  # 出于安全考虑，建议将上述两个重要参数添加至系统全局环境变量，并删除或注释掉此处配置
  # 否则可在网页端向访问者或订阅用户发送推送 https://www.webpushr.com/api-playground
  # 例如GitHub Actions环境变量配置，参数名不变，密钥名自定义，可参考如下
  # env:
  #     webpushrKey: ${{ secrets.WEBPUSHR_KEY }}
  #     webpushrAuthToken: ${{ secrets.WEBPUSHR_AUTH_TOKEN }}
  # 如果您的仓库私有，则无需担心此问题

  trackingCode: "BB9Y-w9p3u0CKA7UP9nupB6I-_NqE2MuODmKJjyC4W2YflX06Ff_hEhrNJfonrut5l6gCa28gC83q2OII7Qv-oA"
  icon: "https://cdn.jsdelivr.net/gh/g0fcn/img/logo.webp" # 必须为192*192 png图片
  # auto_hide: "0" # 默认为 1，代表true，即自动隐藏
  # sort: "date" # 默认为updated，即只要最新文章更改了更新时间即推送新文章，改为date即文章第一次发布时间
  # delay: "30" # 延时推送，考虑到CDN缓存更新，默认定时为在 hexo d 10分钟后推送，单位为分钟（最短时间为5min）
  # expire: "15d" # 推送过期时长，默认值为7天，格式如下：'5m'代表5分钟,'5h'代表5小时, '5d'代表5天.
  # image: # 默认为文章封面，Front-matter 属性为'cover'(butterfly主题友好选项)，如果您没有定义默认封面或此属性，请在这里设置默认image
  action_buttons: # 如果你需要额外自定义按钮 可按照如下格式：
    - title: 阅读全文 # 当 title 未配置时 默认值为 “前往查看”
      # url:  # 当 url 未配置时 默认值为 最新文章链接
    - title: 订阅页面
      url: https://g0f.cn/sub/
    # 但 action_buttons 为未定义时也默认保留了一个按钮，即前往查看，除非设置为 false
    # action_buttons: false # 当设为 false 则不显示额外的按钮

  # 以下配置为按订阅主题推送给不同订阅用户，请按照数组形式，一一对应，具体位置请看使用文档
  categories: [工作, 博客, 工具, 生活, 音乐, 学习]
  segment: ["484223", "484224", "484225", "484226", "484227", "484229"]
  endpoint: segment # 可选配置 all / segment / sid
  # 默认为 segment，即根据不同主题推送细分，同时配置上述选项
  # 官方文档参数见 https://docs.webpushr.com/introduction-to-rest-api
  # 例如 all，即推送至所有用户；针对测试，可只推送给单个用户即自己，同时设置 sid 选项
  # 您也可以将segment 设置为 all-users 对应的ID，同样也可以实现推送至所有用户
  # sid: "130391396" # 单个用户ID 可在控制台查看 https://app.webpushr.com/subscribers

  sw_self: true

  # 此外，在文章 Front-Matter 处
  # 可覆盖 auto_hide 和 expire 配置，针对需要特别提醒文章可以设置不自动隐藏及过期时间延长等操作
  # 以及可指定schedule参数（例如：schedule: 2022-10-01 00:00:00），定时推送
  # 当文章头设置 webpushr: false 时，可关闭本篇文章推送，此参数主要防止久远文章更新推送

swpp:
  enable: true

copyMarkdown:
    enable: true
    pureMarkdown: false #使用true以禁用外挂转换 默认为 false
    keyboard: true #cv悬浮组件
    field: post # default: 每个页面 post: 仅文章页面（默认值）
    copyright: true # 是否添加版权信息 默认开启
    Reprint: true # 是否开启一键转载 默认开启
