image: node:latest
pages:
  stage: deploy
  script:
    - git clone https://github.com/xinkeji/hexo.git public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"